docker push codewisdom/ts-train-service:0.0.4
docker push codewisdom/ts-ui-dashboard:0.0.4
docker push codewisdom/ts-auth-service:0.0.4
docker push codewisdom/ts-user-service:0.0.4
docker push codewisdom/ts-verification-code-service:0.0.4
docker push codewisdom/ts-contacts-service:0.0.4
docker push codewisdom/ts-order-service:0.0.4
docker push codewisdom/ts-order-other-service:0.0.4
docker push codewisdom/ts-config-service:0.0.4
docker push codewisdom/ts-station-service:0.0.4
docker push codewisdom/ts-travel-service:0.0.4
docker push codewisdom/ts-travel2-service:0.0.4
docker push codewisdom/ts-preserve-service:0.0.4
docker push codewisdom/ts-preserve-other-service:0.0.4
docker push codewisdom/ts-basic-service:0.0.4
docker push codewisdom/ts-ticketinfo-service:0.0.4
docker push codewisdom/ts-price-service:0.0.4
docker push codewisdom/ts-notification-service:0.0.4
docker push codewisdom/ts-security-service:0.0.4
docker push codewisdom/ts-inside-payment-service:0.0.4
docker push codewisdom/ts-execute-service:0.0.4
docker push codewisdom/ts-payment-service:0.0.4
docker push codewisdom/ts-rebook-service:0.0.4
docker push codewisdom/ts-cancel-service:0.0.4
docker push codewisdom/ts-route-service:0.0.4
docker push codewisdom/ts-assurance-service:0.0.4
docker push codewisdom/ts-seat-service:0.0.4
docker push codewisdom/ts-travel-plan-service:0.0.4
docker push codewisdom/ts-route-plan-service:0.0.4
docker push codewisdom/ts-food-map-service:0.0.4
docker push codewisdom/ts-food-service:0.0.4
docker push codewisdom/ts-consign-price-service:0.0.4
docker push codewisdom/ts-consign-service:0.0.4
docker push codewisdom/ts-admin-order-service:0.0.4
docker push codewisdom/ts-admin-basic-info-service:0.0.4
docker push codewisdom/ts-admin-route-service:0.0.4
docker push codewisdom/ts-admin-travel-service:0.0.4
docker push codewisdom/ts-admin-user-service:0.0.4
docker push codewisdom/ts-news-service:0.0.4
docker push codewisdom/ts-ticket-office-service:0.0.4
docker push codewisdom/ts-voucher-service:0.0.4
