FROM java:8-jre
MAINTAINER dingding <17212010004@fudan.edu.cn>

ADD ./target/ts-admin-basic-info-service-1.0.jar /app/
CMD ["java", "-Xmx200m", "-jar", "/app/ts-admin-basic-info-service-1.0.jar"]

EXPOSE 18767