---
# Source: rdb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
---
# Source: rdb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
type: Opaque
data:
  mysql-password: "QWJjZDEyMzQj"
  mysql-replication-password: "UmVwbF8xMjM="
---
# Source: rdb/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
data:
  node.cnf: |
    [mysqld]
    default_storage_engine=InnoDB
    max_connections=65535
  server-id.cnf: |
    [mysqld]
    server-id=@@SERVER_ID@@
  create-peers.sh: |
    #!/bin/sh
    set -eu
    i=0
    while [ $i -lt 3 ]
    do
      if [ $i = 0 ]
      then
        echo -n "nacos-rdb-${i}.nacos-rdb.default:8801"
      else
        echo -n ",nacos-rdb-${i}.nacos-rdb.default:8801"
      fi
      i=$((i+1))
    done
  leader-start.sh: |
    #!/usr/bin/env bash
    curl -X PATCH -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/pods/$HOSTNAME \
    -d '[{"op": "replace", "path": "/metadata/labels/role", "value": "leader"}]'
  leader-stop.sh: |
    #!/usr/bin/env bash
    curl -X PATCH -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" -H "Content-Type: application/json-patch+json" \
    --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/default/pods/$HOSTNAME \
    -d '[{"op": "replace", "path": "/metadata/labels/role", "value": "follower"}]'
---
# Source: rdb/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
rules:
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - patch
---
# Source: rdb/templates/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
roleRef:
  kind: Role
  name: nacos-rdb
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: nacos-rdb
---
# Source: rdb/templates/service.yaml
# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: nacos-rdb
  labels:
    app: nacos-rdb
spec:
  ports:
  - name: nacos-rdb
    port: 3306
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: nacos-rdb
---
# Source: rdb/templates/service.yaml
# Client service for connecting to any MySQL instance for writes.
apiVersion: v1
kind: Service
metadata:
  name: nacos-rdb-leader
  labels:
    app: nacos-rdb
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: nacos-rdb
    role: leader
---
# Source: rdb/templates/service.yaml
# Client service for connecting to any MySQL instance for reads.
apiVersion: v1
kind: Service
metadata:
  name: nacos-rdb-follower
  labels:
    app: nacos-rdb
spec:
  type: NodePort
  ports:
  - name: mysql
    port: 3306
    targetPort: mysql
  selector:
    app: nacos-rdb
    role: follower
---
# Source: rdb/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos-rdb
  namespace: default
  labels:
    app: nacos-rdb
spec:
  serviceName: nacos-rdb
  replicas: 3
  selector:
    matchLabels:
      app: nacos-rdb
      release: nacos
  template:
    metadata:
      labels:
        app: nacos-rdb
        release: nacos
        role: candidate
      annotations:
        checksum/config: 63cf6b4f15ca821f9f0cc0a650ac3f7b0f7c4ac4b4ab34011ec62d27d73e4e0d
    spec:
      serviceAccountName: nacos-rdb
      initContainers:
      - name: init-mysql
        image: "busybox:1.32"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        command: ['sh','-c']
        args:
          - |
            # Generate mysql server-id from pod ordinal index.
            ordinal=$(echo $(hostname) | tr -cd "[0-9]")
            # Copy server-id.conf adding offset to avoid reserved server-id=0 value.
            cat /mnt/config-map/server-id.cnf | sed s/@@SERVER_ID@@/$((100 + $ordinal))/g > /mnt/conf.d/server-id.cnf
            # Copy appropriate conf.d files from config-map to config mount.
            cp -f /mnt/config-map/node.cnf /mnt/conf.d/
            cp -f /mnt/config-map/*.sh /mnt/scripts/
            chmod +x /mnt/scripts/*
            # remove lost+found.
            rm -rf /mnt/data/lost+found
        volumeMounts:
          - name: conf
            mountPath: /mnt/conf.d
          - name: scripts
            mountPath: /mnt/scripts
          - name: config-map
            mountPath: /mnt/config-map
          - name: data
            mountPath: /mnt/data
      containers:
      - name: mysql
        image: "radondb/percona:5.7.34"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        env:
        - name: MYSQL_REPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-rdb
              key: mysql-replication-password
        - name: MYSQL_DATABASE
          value: "nacos"
        - name: MYSQL_USER
          value: "nacos"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-rdb
              key: mysql-password
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: conf
          mountPath: /etc/mysql/conf.d
        - name: logs
          mountPath: /var/log/mysql
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - mysqladmin ping -uroot
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - mysql -uroot -e "SELECT 1"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      - name: xenon
        image: "radondb/xenon:1.1.5-helm"
        imagePullPolicy: "IfNotPresent"
        lifecycle:
          postStart:
            exec:
              command: ['sh', '-c', 'until (xenoncli xenon ping && xenoncli cluster add "$(/scripts/create-peers.sh)") > /dev/null 2>&1; do sleep 2; done']
        resources:
          {}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        env:
        - name: MYSQL_REPL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nacos-rdb
              key: mysql-replication-password
        - name: POD_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST
          value: $(POD_HOSTNAME).nacos-rdb.default
        - name: LEADER_START_CMD
          value: "/scripts/leader-start.sh"
        - name: LEADER_STOP_CMD
          value: "/scripts/leader-stop.sh"
        - name: Master_SysVars
          value: "sync_binlog=default;innodb_flush_log_at_trx_commit=default"
        - name: Slave_SysVars
          value: "sync_binlog=1000;innodb_flush_log_at_trx_commit=1"
        ports:
        - name: xenon
          containerPort: 8801
        livenessProbe:
          exec:
            command:
              - pgrep
              - xenon
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "xenoncli xenon ping"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
      - name: slowlog
        image: "busybox:1.32"
        imagePullPolicy: "IfNotPresent"
        resources:
          {}
        command:
        - "tail"
        - "-f"
        - "/logs/mysql-slow.log"
        volumeMounts:
        - name: logs
          mountPath: /logs
      volumes:
      - name: conf
        emptyDir: {}
      - name: scripts
        emptyDir: {}
      - name: logs
        emptyDir: {}
      - name: config-map
        configMap:
          name: nacos-rdb
  volumeClaimTemplates:
  - metadata:
      name: data
      annotations:
    spec:
      accessModes:
      - "ReadWriteOnce"
      resources:
        requests:
          storage: "1Gi"
